### ISSUE TITLE
Cannot install using go get

### ISSUE THREAD

**Issue by ghost** [logdna/logdna-go#19]
When I run 

`go get github.com/logdna/logdna-go`

The following is output:

```
go: github.com/logdna/logdna-go@v1.0.0: parsing go.mod:
	module declares its path as: logdna
	        but was required as: github.com/logdna/logdna-go
```

**Comment by darinspivey** [comment]
Thanks for reporting this. We are working on fixing the issue which was most likely caused during a module name change that happened some time ago during pre-release.  Stay tuned!

**Comment by mdeltito** [comment]
Thanks @tmstn, this should be resolved now - there was a tag missing for the `HEAD` commit, which fell out of the go proxy cache. We've pushed a v1.0.2 tag that is now available.

I would like to note that this package is still a work in progress, but please feel free to provide feedback on the current version. We have work planned in the coming months around the resiliency of the client during network disruption, and cleanup of the public interface which may incur some (relatively minor) breaking changes. Stay tuned, and thanks again for reporting this!

**Comment by ghost** [comment]
Thanks. Do you have any idea of the timescales in which this package would become production ready?
